version: '3.8'

services:
  nginx-proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php-backend
      - flask-frontend
    networks:
      - app-network

  php-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  flask-frontend:
    image: maeddes/frontendflask:hse24
    environment:
      - API_URL=http://php-backend:80/shopping
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=shopping
      - MYSQL_USER=shopping
      - MYSQL_PASSWORD=shopping
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: