apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
      CREATE TABLE IF NOT EXISTS shopping_items (
          id BIGINT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          amount INT NOT NULL
      );
      INSERT INTO shopping_items (name, amount) VALUES 
          ('Apple', 5),
          ('Banana', 3),
          ('Milk', 2);