apiVersion: v1
kind: Service
metadata:
  name: php-backend
spec:
  selector:
    app: php-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30480
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend
spec:
  selector:
    app: flask-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort  # This makes it accessible from outside the cluster